/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 05-08-2019 12.50
 */
import static ratpack.groovy.Groovy.ratpack

ratpack {
	// cors headers
	include 'modules/cors.groovy'

	// external file conf
	include 'modules/server-config.groovy'

	// fake business logic module
	include 'modules/business-stub.groovy'

	// logging (have to be the last one)
	include 'modules/request-log.groovy'
}
