/*
 * This ratpack file was auto generated by 'gigawatt'
 * @author d7392
 * @date 05-08-2019 12.50
 */
// external
import static ratpack.groovy.Groovy.ratpack
// internal

ratpack {
	handlers {
		get {
			render 'This application was auto generated by "gigawatt"'
		}
	}
}
